#!/bin/bash

#APP 相关
export APP_NAME=SsoCenter
export APP_ROOT=/usr/bale/deploy/$APP_NAME
export APP_PROCESS_NAME=$APP_NAME-0
export APP_LOG_DIR=$APP_ROOT/$APP_PROCESS_NAME/log
mkdir -p $APP_LOG_DIR

export CATALINA_BASE=$APP_ROOT
export CATALINA_LOG_DIR=$APP_LOG_DIR/tomcatlog
mkdir -p $CATALINA_LOG_DIR
export CATALINA_OUT=$CATALINA_LOG_DIR/catalina.out

JAVA_OPTS="-Dfile.encoding=UTF-8"
JAVA_OPTS="$JAVA_OPTS -Dlog.dir=$APP_LOG_DIR"
JAVA_OPTS="$JAVA_OPTS -DTOMCAT_LOG_DIR=$CATALINA_LOG_DIR -DNFW=$APP_PROCESS_NAME -Dprocname=$APP_PROCESS_NAME "
#JAVA_OPTS="$JAVA_OPTS -DTOMCAT_LOG_DIR=$CATALINA_LOG_DIR  -DTOMCAT_WORK_DIR=$TOMCAT_WORK_DIR -DNFW=$APP_PROCESS_NAME -Dprocname=$APP_PROCESS_NAME "
export JAVA_OPTS="$JAVA_OPTS"

bash $CATALINA_HOME/bin/catalina.sh start
